SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
SHELL_RADIUS = 300
ELECTRON_RADIUS = 10
NO_ELECTRONS = 5

STATIC_CONSTANT = int(1e7) 
DEGREES_PER_FRAME = 25 

LARGE_FONT_SIZE = 36
SMALL_FONT_SIZE = 18
FONT = "libertinus.ttf"
